version: '3'
services:
  frontend:
    image: node:lts-alpine
    container_name: frontend
    command: sh /app/frontend_setup.sh
    volumes:
      - .:/app
    expose:
      - "8080"
    ports:
      - "8080:8080"
 